In [1]:
import pandas as pd
df=pd.read_csv('customer_shopping_behavior.csv')

In [17]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')

In [20]:
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'review_rating'],
      dtype='object')

In [6]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [7]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [9]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [10]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [11]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [12]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')

In [13]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [19]:
labels=['Young Adult','Adult','Middle-Age','Senior']
df['age_group']=pd.qcut((df['age']),q=4,labels=labels)

In [20]:
df[['age_group','age']].head()

     age_group  age
0   Middle-Age   55
1  Young Adult   19
2   Middle-Age   50
3  Young Adult   21
4   Middle-Age   45

In [38]:
frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Annually':365,
    'Every 3 Months':90,
    'Quarterly':90,
    'Monthly':30,
    'Bi-Weekly':14
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [39]:
df[['purchase_frequency_days','frequency_of_purchases']]

      purchase_frequency_days frequency_of_purchases
0                          14            Fortnightly
1                          14            Fortnightly
2                           7                 Weekly
3                           7                 Weekly
4                         365               Annually
...                       ...                    ...
3895                        7                 Weekly
3896                       14              Bi-Weekly
3897                       90              Quarterly
3898                        7                 Weekly
3899                       90              Quarterly

[3900 rows x 2 columns]

In [33]:
df.rename(columns={'purchase_amount_(usd)':'purchase_amount'},inplace=True)

In [34]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchase_frequency_days'],
      dtype='object')

In [40]:
df=df.drop('promo_code_used',axis=1)

In [41]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [42]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [43]:
from sqlalchemy import create_engine
import pandas as pd

# MySQL details
username = "root"
password = "sql2025"     # your password
host = "localhost"
database = "customer_behavior"

# Create engine
engine = create_engine(
    f"mysql+mysqlconnector://{username}:{password}@{host}/{database}"
)

print("Connected to MySQL successfully")

Connected to MySQL successfully

In [44]:
df.to_sql(
    name="customer",     # table name
    con=engine,
    if_exists="replace", # replace if table exists
    index=False
)

print("Data imported successfully into MySQL")

Data imported successfully into MySQL